export const ROLES = {
  ADMIN: "ADMIN",
  CHEF_DE_DEPARTEMENT: "CHEF_DE_DEPARTEMENT",
  CHEF_DE_FILIERE: "CHEF_DE_FILIERE",
  PROFESSEUR: "PROFESSEUR",
  ETUDIANT: "ETUDIANT"
}

export const UTILISATEUR_GROUPES = {
  ADMIN: "ADMIN",
  NORMAL: "NORMAL",
}